OPTIONS (skip=1)
LOAD DATA
INFILE community_provision_data.csv
REPLACE
INTO TABLE COMMUNITY_PROVISION
FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(COMMUNITY_ID, COMMUNITY_CENTRE, LIBRARIES, GREENSPACE_DIST, GREENSPACE_QUAL,CHI, DATAZONE TERMINATED BY WHITESPACE)
