OPTIONS (skip=1)
LOAD DATA
INFILE park_data_loc.csv
REPLACE
INTO TABLE PARKS
FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(NAME, CLASSIFICATION, POST, XCOORD, YCOORD, DATAZONE TERMINATED BY WHITESPACE)
