OPTIONS (skip=1)
LOAD DATA
INFILE simd_data_proj.csv
REPLACE
INTO TABLE SIMD
FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(DATAZONE, DZNAME, LANAME, XCOORD, YCOORD, SIMD_RANK, SIMD_QUANTILE TERMINATED BY WHITESPACE)
